package:
  name: invisibleroads-macros
  version: "0.7.0"

source:
  fn: invisibleroads-macros-0.7.0.tar.gz
  url: https://pypi.python.org/packages/d1/3d/7be96055628e67cd00c3229f92a9a27b0cad622fa890ee8da7e90f85f5ce/invisibleroads-macros-0.7.0.tar.gz
  md5: 6393b4de33fca0d20b50e8cf367ecaf7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - invisibleroads-macros = invisibleroads-macros:main
    #
    # Would create an entry point called invisibleroads-macros that calls invisibleroads-macros.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pathlib
    - python-dateutil
    - six

  run:
    - python
    - pathlib
    - python-dateutil
    - six

test:
  # Python imports
  imports:
    - invisibleroads_macros

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://invisibleroads.com
  license: MIT License
  summary: 'Shortcut functions'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
