package:
  name: sequencer
  version:  0.3.1

source:
  git_tag: v0.3.1
  git_url: https://github.com/SEL-Columbia/sequencer.git
  # path: /root/Projects/sequencer


requirements:
  build:
    - python
    - setuptools
    - dateutil
    - decorator
    - fiona
    - freetype
    - gdal
    - libpng
    - matplotlib
    - networkx
    - numexpr
    - numpy
    - pandas
    - pyparsing
    - pytz
    - scipy

  run:
    - python
    - dateutil
    - decorator
    - fiona
    - freetype
    - gdal
    - libpng
    - matplotlib
    - networkx
    - numexpr
    - numpy
    - pandas
    - pyparsing
    - pytz
    - scipy

test:
  # Python imports
  imports:
    - sequencer

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/SEL-Columbia/Sequencer
  
  license:  MIT
  summary: "Python library for sequencing the output of Network Planner csv's and shape file outputs"

