package:
  name: infrastructure-planning 
  version:  2.1.0

source:
  # git_tag: 2.1.0
  git_url: https://github.com/SEL-Columbia/infrastructure-planning.git
  # path: /home/cjn/src/infrastructure-planning

build:
  preserve_egg_dir: yes

test:
  requires:
    - pytest

requirements:
  build:
    - pytest-runner
    - python
    - pathlib
    - python-dateutil
    - six
    - numpy
    - pandas
    - networkx
    - scipy
    - libgdal
    - gdal
    - rtree
    - scikit-learn
    - sequencer
    - networker
    - shapely
    - geopy
    - simplejson
    - geometryio

  run:
    - python
    - pathlib
    - python-dateutil
    - six
    - numpy
    - pandas
    - networkx
    - scipy
    - libgdal
    - gdal
    - rtree
    - scikit-learn
    - sequencer
    - networker
    - shapely
    - geopy
    - simplejson
    - geometryio

about:
  home: https://github.com/SEL-Columbia/infrastructure-planning
  
  license: WTFPL
  summary: "Python library for planning infrastructure"
