package:
  name: infrastructure-planning 
  version:  2.1.0

source:
  # git_url: https://github.com/SEL-Columbia/infrastructure-planning.git
  path: /root/Projects/infrastructure-planning

build:
  preserve_egg_dir: yes

requirements:
  build:
    - numpy 1.11.1
    - pandas 0.18.1
    - networkx 1.11
    - scipy 0.17.0
    - gdal 2.1.0
    - rtree 0.8.2
    - scikit-learn
    - sequencer
    - networker
    - shapely

  run:
    - numpy 1.11.1
    - pandas 0.18.1
    - networkx 1.11
    - scipy 0.17.0
    - gdal 2.1.0
    - rtree 0.8.2
    - scikit-learn
    - sequencer
    - networker
    - shapely

about:
  home: https://github.com/SEL-Columbia/infrastructure-planning
  
  license: WTFPL
  summary: "Python library for planning infrastructure"
