package:
  name: infrastructure-planning 
  version:  3.0.1.2

source:
  # git_tag: 3.0.1
  # git_url: https://github.com/SEL-Columbia/infrastructure-planning.git
  path: /home/cjn/src/infrastructure-planning

build:
  preserve_egg_dir: yes

test:
  requires:
    - pytest

requirements:
  build:
    # for invisibleroads-macros
    - attrs
    - configparser
    # for infrastructure-planning
    - pytest-runner
    - python
    - pathlib
    - python-dateutil
    - six
    - numpy
    - pandas
    - networkx ==1.11
    - scipy
    - gdal
    - rtree
    - scikit-learn
    - sequencer
    - networker
    - shapely
    - geopy
    - simplejson
    - geometryio

  run:
    # for invisibleroads-macros
    - attrs
    - configparser
    # for infrastructure-planning
    - python
    - pathlib
    - python-dateutil
    - six
    - numpy
    - pandas
    - networkx ==1.11
    - scipy
    - gdal
    - rtree
    - scikit-learn
    - sequencer
    - networker
    - shapely
    - geopy
    - simplejson
    - geometryio

about:
  home: https://github.com/SEL-Columbia/infrastructure-planning
  
  license: WTFPL
  summary: "Python library for planning infrastructure"
