package:
  name: modelrunner 
  version:  0.7.0

source:
  git_tag: v0.7.0
  git_url: https://github.com/SEL-Columbia/modelrunner.git
  # path: /home/cjn/src/modelrunner

build:
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - redis
    - redis-py
    - six
    - tornado
    - futures
    - psutil

  run:
    - python
    - setuptools
    - redis
    - redis-py
    - six
    - tornado
    - futures
    - psutil

test:
  imports:
    - modelrunner 

about:
  home: https://github.com/SEL-Columbia/modelrunner
  
  license: WTFPL
  summary: "System for managing long running model jobs"

