package:
  name: modelrunner 
  version:  0.4.7

source:
  # NOTE:  Build from local path until this is stable 
  # git_url: https://github.com/SEL-Columbia/modelrunner.git
  path: /home/cjn/src/modelrunner

build:
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - redis
    - redis-py
    - tornado
    - futures
    - psutil

  run:
    - python
    - setuptools
    - redis
    - redis-py
    - tornado
    - futures
    - psutil

test:
  imports:
    - modelrunner 

about:
  home: https://github.com/SEL-Columbia/modelrunner
  
  license: WTFPL
  summary: "System for managing long running model jobs"

