package:
  name: networker
  version:  0.2.6

source:
  # NOTE:  Built from local path because I needed to temporarily remove 
  #        dateutil from requirements.txt in networker repo.
  #        Hopefully this problem will be resolved going forward.
  # git_url: https://github.com/SEL-Columbia/networker.git
  path: /home/cjn/src/networker

build:
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - gdal
    - numpy 1.9.3
    - scipy 0.17.0
    - networkx 1.11
    - decorator 4.0.9
    - cython 0.24
    - nose 1.3.7
    - numba 0.20.0
    - llvmlite 0.6.0
    - funcsigs 0.4
    - pandas 0.17.1
    - enum34 1.1.2
    - dateutil 
    - pytz 2016.3
    - rtree 0.8.2
    - jsonschema 2.4.0
    - pyproj 1.9.5.1
    - six 1.10.0

  run:
    - python
    - setuptools
    - gdal
    - numpy 1.9.3
    - scipy 0.17.0
    - networkx 1.11
    - decorator 4.0.9
    - cython 0.24
    - nose 1.3.7
    - numba 0.20.0
    - llvmlite 0.6.0
    - funcsigs 0.4
    - pandas 0.17.1
    - enum34 1.1.2
    - dateutil 
    - pytz 2016.3
    - rtree 0.8.2
    - jsonschema 2.4.0
    - pyproj 1.9.5.1
    - six 1.10.0

test:
  imports:
    - networker

about:
  home: https://github.com/SEL-Columbia/networker
  
  license: WTFPL
  summary: "Python library for planning distribution networks"

