package:
  name: geometryio
  version: "0.9.7.6"

source:
  fn: geometryIO-0.9.7.6.tar.gz
  url: https://pypi.python.org/packages/5c/5a/7c641b4298d99005a649e8c86b47947ad86ff2bdb3669b99ce2f99b77c14/geometryIO-0.9.7.6.tar.gz
  md5: f7ddd8bfe2d10f4fc9273ec7533cf559
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - geometryio = geometryio:main
    #
    # Would create an entry point called geometryio that calls geometryio.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - archiveio
    - gdal
    - shapely

  run:
    - python
    - archiveio
    - gdal
    - shapely

about:
  home: https://github.com/invisibleroads/geometryIO
  license: MIT License
  summary: 'GDAL wrapper for reading and writing geospatial data to a variety of vector formats'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
